// Generated by CoffeeScript 1.9.3
(function() {
  var getPathForInput, getPathsForInputs, parsePath;

  getPathsForInputs = function(inputs) {
    var paths;
    return paths = inputs.map(function(input) {
      var parsedPath, path;
      path = input.output.metadata.wallet_path;
      return parsedPath = parsePath(path);
    });
  };

  parsePath = function(path) {
    var indices, parts;
    parts = path.split('/');
    return indices = parts.slice(1).map(function(index) {
      return parseInt(index);
    });
  };

  getPathForInput = function(paymentResource, index) {
    var path;
    path = paymentResource.inputs[index].output.metadata.wallet_path;
    return parsePath(path);
  };

  module.exports = {
    getPathsForInputs: getPathsForInputs,
    parsePath: parsePath,
    getPathForInput: getPathForInput
  };

}).call(this);
