// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {
    crypto: {
      PassphraseBox: require("./crypto/hybrid_box")
    },
    bit: {
      MultiWallet: require("./bit/multiwallet"),
      transaction_utils: require("./bit/transaction_utils")
    }
  };

}).call(this);
