// Generated by CoffeeScript 1.8.0
(function() {
  var AESBox, HybridBox, PassphraseBox;

  PassphraseBox = require('./passphrase_box');

  AESBox = require('./aes_box');

  module.exports = HybridBox = (function() {
    HybridBox.encrypt = function(passphrase, plaintext, callback) {
      return AESBox.encrypt(passphrase, plaintext, callback);
    };

    HybridBox.decrypt = function(passphrase, encrypted, callback) {
      var iv, plaintext;
      iv = encrypted.iv;
      if (iv != null) {
        return AESBox.decrypt(passphrase, encrypted, callback);
      } else {
        plaintext = PassphraseBox.decrypt(passphrase, encrypted);
        return callback(null, plaintext);
      }
    };

    function HybridBox(_arg, callback) {
      var iterations, passphrase, salt;
      passphrase = _arg.passphrase, salt = _arg.salt, iterations = _arg.iterations;
      new AESBox({
        passphrase: passphrase,
        salt: salt,
        iterations: iterations
      }, callback);
    }

    return HybridBox;

  })();

}).call(this);
