// Generated by CoffeeScript 1.8.0
(function() {
  var PassphraseBox, crypto, pbkdf2;

  crypto = require("crypto");

  pbkdf2 = require("./pbkdf2");

  module.exports = PassphraseBox = (function() {
    var ITERATIONS;

    ITERATIONS = 100000;

    PassphraseBox.encrypt = function(_arg, callback) {
      var iterations, passphrase, plaintext, salt;
      passphrase = _arg.passphrase, plaintext = _arg.plaintext, salt = _arg.salt, iterations = _arg.iterations;
      return new this({
        passphrase: passphrase,
        salt: salt,
        iterations: iterations
      }, function(error, box) {
        if (error) {
          return callback(error);
        }
        return callback(null, box.encrypt(plaintext));
      });
    };

    PassphraseBox.decrypt = function(_arg, callback) {
      var ciphertext, encrypted, iterations, iv, passphrase, salt;
      passphrase = _arg.passphrase, encrypted = _arg.encrypted;
      salt = encrypted.salt, iterations = encrypted.iterations, iv = encrypted.iv, ciphertext = encrypted.ciphertext;
      return new this({
        passphrase: passphrase,
        salt: salt,
        iterations: iterations
      }, function(error, box) {
        if (error) {
          return callback(error);
        }
        return callback(null, box.decrypt(ciphertext, iv));
      });
    };

    function PassphraseBox(_arg, callback) {
      var passphrase, salt;
      passphrase = _arg.passphrase, salt = _arg.salt, this.iterations = _arg.iterations;
      if (salt) {
        this.salt = Buffer.isBuffer(salt) ? salt : new Buffer(salt, "hex");
      } else {
        try {
          this.salt = crypto.randomBytes(16);
        } catch (_error) {
          throw new Error("Error generating random bytes");
        }
      }
      if (this.iterations == null) {
        this.iterations = ITERATIONS;
      }
      pbkdf2(passphrase, this.salt, this.iterations, 64, (function(_this) {
        return function(error, buffer) {
          if (error) {
            return callback(error);
          }
          _this.aes_key = new Buffer(new Uint8Array(buffer.slice(0, 32)));
          _this.hmac_key = new Buffer(new Uint8Array(buffer.slice(32, 64)));
          return callback(null, _this);
        };
      })(this));
    }

    PassphraseBox.prototype.encrypt = function(plaintext, iv) {
      var aes, ciphertext, encrypted, ivBuf, mac;
      try {
        if (iv == null) {
          iv = crypto.randomBytes(16);
        }
      } catch (_error) {
        throw new Error("Error generating random bytes");
      }
      if (typeof iv === 'string') {
        ivBuf = new Buffer(iv, 'hex');
      } else {
        ivBuf = iv;
      }
      aes = crypto.createCipheriv('aes-256-cbc', this.aes_key, ivBuf);
      aes.setAutoPadding(false);
      encrypted = aes.update(plaintext, 'utf8');
      encrypted = Buffer.concat([encrypted, aes.final()]);
      mac = crypto.createHmac('sha256', this.hmac_key).update(Buffer.concat([ivBuf, encrypted])).digest();
      ciphertext = Buffer.concat([encrypted, mac]);
      return {
        iterations: this.iterations,
        salt: this.salt.toString("hex"),
        iv: ivBuf.toString("hex"),
        ciphertext: ciphertext.toString("hex")
      };
    };

    PassphraseBox.prototype.decrypt = function(cipherData, iv) {
      var aes, cipherDataBuf, ciphertext, decrypted, hmacNew, hmacOld, ivBuf;
      cipherDataBuf = new Buffer(cipherData, 'hex');
      ivBuf = new Buffer(iv, 'hex');
      ciphertext = cipherDataBuf.slice(0, -32);
      hmacOld = cipherDataBuf.slice(-32).toString('hex');
      hmacNew = crypto.createHmac('sha256', this.hmac_key).update(Buffer.concat([ivBuf, ciphertext])).digest().toString('hex');
      if (hmacOld !== hmacNew) {
        throw new Error('Invalid authentication code - this ciphertext may have been tampered with');
      }
      aes = crypto.createDecipheriv('aes-256-cbc', this.aes_key, ivBuf);
      aes.setAutoPadding(false);
      decrypted = aes.update(ciphertext, 'hex', 'utf8');
      return decrypted += aes.final('utf8');
    };

    return PassphraseBox;

  })();

}).call(this);
